# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a1b8e3aa3874253d8eac29698ad5dfbbc9d0847da88982591ab3836258bc44f0a73fa9626a1cdcf4775d34de480d8ad3c6795c3e368ec1e3e496ff78ecc57e2

test:
  secret_key_base: c5c9656de2904ce7b1043ecbe15e7454ed08616e764cfd5bc51c2e275249af4b5906aec640ba71e1630f57a4beb7223d01be393d6a41a509d5f9d868b89a7581

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
